version: '3.8'

services:

  web:
    build:
      context: ./infra/backend
      dockerfile: Dockerfile
    ports:
      - 8182:80
    volumes:
      - .:/var/www/html
    links:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mauFJcuf5dhRMQrjj
      DB_NAME: xylene_db
    networks:
      - xylene-network

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=xylene_db
      - MYSQL_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - 3309:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - xylene-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mauFJcuf5dhRMQrjj
    networks:
      - xylene-network

networks:
  xylene-network:

volumes:
  db:
    driver: local
