services:
  dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    calls:
      - [ addSubscriber, ["@router.listener"]]
#      - [ addListener , ["kernel.view", ["@templating.listener", "onKernelView" ]] ]