services:

  templating.twig_loader:
    class: Twig_Loader_Filesystem
    arguments: [ "%app_root%/src/App/View" ]

  templating.twig:
    class: Twig_Environment
    arguments: [ "@templating.twig_loader" ]

  templating.listener:
    class: Xylene\Listener\ViewListener
    arguments: ["@templating.twig"]